In [ ]:
pip install torch --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch
  Downloading https://download-r2.pytorch.org/whl/cu121/torch-2.5.1%2Bcu121-cp312-cp312-linux_x86_64.whl (780.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.4/780.4 MB 680.3 kB/s eta 0:00:0000:0100:01
Collecting filelock (from torch)
  Using cached filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch) (4.15.0)
Collecting networkx (from torch)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Downloading https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec (from torch)
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 19.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 3.8 MB/s eta 0:00:0000:01
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 24.0 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 665.5 kB/s eta 0:00:0000:0100:01
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 1.1 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 4.4 MB/s eta 0:00:0000:0100:01
Collecting nvidia-curand-cu12==10.3.2.106 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 10.0 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 2.9 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 2.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://download.pytorch.org/whl/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 2.6 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nvtx-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 573.9 kB/s eta 0:00:00a 0:00:01
Collecting triton==3.1.0 (from torch)
  Downloading https://download-r2.pytorch.org/whl/triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.6/209.6 MB 2.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: setuptools in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch) (69.5.1)
Collecting sympy==1.13.1 (from torch)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch)
  Downloading https://download.pytorch.org/whl/nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading https://download.pytorch.org/whl/markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 11.1 MB/s eta 0:00:0000:0100:01
Using cached filelock-3.25.2-py3-none-any.whl (26 kB)
Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 1.2 MB/s eta 0:00:00:00:01
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Downloading https://download.pytorch.org/whl/markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Downloading https://download.pytorch.org/whl/nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 16.9 MB/s eta 0:00:00:00:0100:01
Installing collected packages: mpmath, sympy, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, MarkupSafe, fsspec, filelock, triton, nvidia-cusparse-cu12, nvidia-cudnn-cu12, jinja2, nvidia-cusolver-cu12, torch
Successfully installed MarkupSafe-3.0.3 filelock-3.25.2 fsspec-2026.2.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.6.1 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.9.86 nvidia-nvtx-cu12-12.1.105 sympy-1.13.1 torch-2.5.1+cu121 triton-3.1.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
%pip install neuralforecast

Collecting neuralforecast
  Downloading neuralforecast-3.1.7-py3-none-any.whl.metadata (14 kB)
Collecting coreforecast>=0.0.6 (from neuralforecast)
  Downloading coreforecast-0.0.17-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.6 kB)
Requirement already satisfied: fsspec in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from neuralforecast) (2026.2.0)
Requirement already satisfied: numpy>=1.21.6 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from neuralforecast) (2.2.4)
Requirement already satisfied: pandas>=1.3.5 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from neuralforecast) (2.2.2)
Requirement already satisfied: scipy in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from neuralforecast) (1.15.2)
Requirement already satisfied: torch>=2.4.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from neuralforecast) (2.5.1+cu121)
Requirement already satisfied: tornado>=6.5.5 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from neuralforecast) (6.5.5)
Collecting pytorch-lightning>=2.0.0 (from neuralforecast)
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Collecting ray>=2.2.0 (from ray[train,tune]>=2.2.0->neuralforecast)
  Downloading ray-2.55.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (21 kB)
Collecting optuna (from neuralforecast)
  Using cached optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Collecting utilsforecast>=0.2.3 (from neuralforecast)
  Downloading utilsforecast-0.2.16-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from pandas>=1.3.5->neuralforecast) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from pandas>=1.3.5->neuralforecast) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from pandas>=1.3.5->neuralforecast) (2026.2)
Requirement already satisfied: tqdm>=4.57.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from pytorch-lightning>=2.0.0->neuralforecast) (4.67.3)
Collecting PyYAML>5.4 (from pytorch-lightning>=2.0.0->neuralforecast)
  Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting torchmetrics>0.7.0 (from pytorch-lightning>=2.0.0->neuralforecast)
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: packaging>=23.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from pytorch-lightning>=2.0.0->neuralforecast) (26.2)
Requirement already satisfied: typing-extensions>4.5.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from pytorch-lightning>=2.0.0->neuralforecast) (4.15.0)
Collecting lightning-utilities>=0.10.0 (from pytorch-lightning>=2.0.0->neuralforecast)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click>=7.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (8.3.3)
Requirement already satisfied: filelock in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (3.25.2)
Requirement already satisfied: jsonschema in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (4.26.0)
Collecting msgpack<2.0.0,>=1.0.0 (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast)
  Using cached msgpack-1.1.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Collecting protobuf>=3.20.3 (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast)
  Using cached protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: requests in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2.33.1)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from ray[train,tune]>=2.2.0->neuralforecast) (2.13.3)
Collecting tensorboardX>=1.9 (from ray[train,tune]>=2.2.0->neuralforecast)
  Using cached tensorboardx-2.6.5-py3-none-any.whl.metadata (6.6 kB)
Collecting pyarrow>=9.0.0 (from ray[train,tune]>=2.2.0->neuralforecast)
  Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: networkx in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (3.6.1)
Requirement already satisfied: jinja2 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (3.1.0)
Requirement already satisfied: setuptools in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (69.5.1)
Requirement already satisfied: sympy==1.13.1 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from torch>=2.4.0->neuralforecast) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.4.0->neuralforecast) (12.9.86)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from sympy==1.13.1->torch>=2.4.0->neuralforecast) (1.3.0)
Requirement already satisfied: narwhals>=2.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from utilsforecast>=0.2.3->neuralforecast) (2.20.0)
Collecting alembic>=1.5.0 (from optuna->neuralforecast)
  Using cached alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna->neuralforecast)
  Using cached colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Collecting sqlalchemy>=1.4.2 (from optuna->neuralforecast)
  Using cached sqlalchemy-2.0.49-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting Mako (from alembic>=1.5.0->optuna->neuralforecast)
  Downloading mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast)
  Using cached aiohttp-3.13.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[train,tune]>=2.2.0->neuralforecast) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[train,tune]>=2.2.0->neuralforecast) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[train,tune]>=2.2.0->neuralforecast) (0.4.2)
Requirement already satisfied: six>=1.5 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.5->neuralforecast) (1.17.0)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna->neuralforecast)
  Downloading greenlet-3.5.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from jinja2->torch>=2.4.0->neuralforecast) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (0.30.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2026.4.22)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast)
  Using cached frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast)
  Using cached multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast)
  Using cached propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast)
  Using cached yarl-1.23.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Downloading neuralforecast-3.1.7-py3-none-any.whl (286 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.0/287.0 kB 1.4 MB/s eta 0:00:00:00:01
Downloading coreforecast-0.0.17-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (348 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.2/348.2 kB 1.8 MB/s eta 0:00:00:00:01
Downloading pytorch_lightning-2.6.1-py3-none-any.whl (857 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 857.3/857.3 kB 5.2 MB/s eta 0:00:00:00:01
Downloading ray-2.55.1-cp312-cp312-manylinux2014_x86_64.whl (73.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.8/73.8 MB 5.1 MB/s eta 0:00:000:00:0100:01
Downloading utilsforecast-0.2.16-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.6/46.6 kB 151.3 kB/s eta 0:00:00a 0:00:01
Using cached optuna-4.8.0-py3-none-any.whl (419 kB)
Using cached alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading lightning_utilities-0.15.3-py3-none-any.whl (31 kB)
Using cached msgpack-1.1.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (427 kB)
Downloading protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl (324 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.3/324.3 kB 1.8 MB/s eta 0:00:00:00:01
Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 8.7 MB/s eta 0:00:000:00:0100:01
Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
Using cached sqlalchemy-2.0.49-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
Using cached tensorboardx-2.6.5-py3-none-any.whl (87 kB)
Downloading torchmetrics-1.9.0-py3-none-any.whl (983 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 9.4 MB/s eta 0:00:00:00:01
Using cached colorlog-6.10.1-py3-none-any.whl (11 kB)
Using cached aiohttp-3.13.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
Downloading greenlet-3.5.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (611 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 611.4/611.4 kB 6.3 MB/s eta 0:00:00:00:01
Downloading mako-1.3.12-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 354.8 kB/s eta 0:00:00a 0:00:01
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
Using cached multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (256 kB)
Using cached propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (221 kB)
Using cached yarl-1.23.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (100 kB)
Installing collected packages: PyYAML, pyarrow, protobuf, propcache, multidict, msgpack, Mako, lightning-utilities, greenlet, frozenlist, coreforecast, colorlog, aiohappyeyeballs, yarl, tensorboardX, sqlalchemy, aiosignal, utilsforecast, alembic, aiohttp, torchmetrics, ray, optuna, pytorch-lightning, neuralforecast
Successfully installed Mako-1.3.12 PyYAML-6.0.3 aiohappyeyeballs-2.6.1 aiohttp-3.13.5 aiosignal-1.4.0 alembic-1.18.4 colorlog-6.10.1 coreforecast-0.0.17 frozenlist-1.8.0 greenlet-3.5.0 lightning-utilities-0.15.3 msgpack-1.1.2 multidict-6.7.1 neuralforecast-3.1.7 optuna-4.8.0 propcache-0.4.1 protobuf-7.34.1 pyarrow-24.0.0 pytorch-lightning-2.6.1 ray-2.55.1 sqlalchemy-2.0.49 tensorboardX-2.6.5 torchmetrics-1.9.0 utilsforecast-0.2.16 yarl-1.23.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import time
import numpy as np
import pandas as pd
import json

from sklearn.metrics import mean_absolute_error, mean_squared_error

# === CarbonTracker ===
import io
import re
from contextlib import redirect_stdout
from carbontracker.tracker import CarbonTracker as Tracker

# === Eco2AI ===
import eco2ai
eco2ai_tracker = eco2ai.Tracker(project_name="eco2ai", file_name="eco2ai_emissions_dl.csv", ignore_warnings=True)

/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/carbontracker/components/gpu/nvidia.py:13: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml

In [ ]:
from neuralforecast import NeuralForecast
from neuralforecast.models import TCN, NBEATS, Autoformer

/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-05-04 06:50:25,215	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2026-05-04 06:50:25,353	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

In [ ]:
class CarbonTracker:
  def __init__(self, epochs=1, verbose=1):
    self.epochs = epochs
    self.verbose = verbose
    self.buffer = io.StringIO()
    self.tracker = None
    self.co2_g = None
    self.energy_kwh = None

  def __enter__(self):
    self._stdout_ctx = redirect_stdout(self.buffer)
    self._stdout_ctx.__enter__()
    self.tracker = Tracker(epochs=self.epochs, verbose=self.verbose)
    self.tracker.epoch_start()
    return self

  def __exit__(self, exc_type, exc, tb):
    self.tracker.epoch_end()
    self.tracker.stop()
    self._stdout_ctx.__exit__(exc_type, exc, tb)
    output = self.buffer.getvalue()

    match_co2 = re.search(r"CO2eq:\s*([\d\.]+)\s*g", output)
    self.co2_g = float(match_co2.group(1)) if match_co2 else None

    match_energy = re.search(r"Energy:\s*([\d\.]+)\s*kWh", output)
    self.energy_kwh = float(match_energy.group(1)) if match_energy else None

In [ ]:
def load_series(path, unique_id="series_1"):
    df = pd.read_csv(path, index_col='date')
    df = df.reset_index().rename(columns={'date': 'ds', 'value': 'y'})
    df['unique_id'] = unique_id
    df["ds"] = pd.to_datetime(df["ds"])    # Precisei adicionar pra ML

    return df

def smape(y_true, y_pred, decimals: int = 2) -> float:
    numerator = np.abs(y_true - y_pred)
    denominator = (np.abs(y_true) + np.abs(y_pred)) / 2
    return round(float(np.mean(numerator / (denominator + 1e-10)) * 100), decimals)

def run_forecast(train_df, true_df, freq, season_length, dataset_name):
  results = []

  input_size = len(train_df) - 1
  horizon = len(true_df)

  models = [
        ("TCN", TCN(input_size=input_size, h=horizon, max_steps=700)),
        ("NBEATS", NBEATS(input_size=input_size, h=horizon, max_steps=700)),
        ("AUTOFORMER", Autoformer(input_size=input_size, h=horizon, max_steps=700))
  ]

  for model_name, model in models:

    print("Rodando Modelo: ", model_name, "pro Dataset: ", dataset_name)

    nf = NeuralForecast(
      models=[model],
      freq=freq
    )

    eco2ai_tracker.start()

    with CarbonTracker() as carbontracker:
      start = time.time()

      nf.fit(train_df)
      forecast = nf.predict(h=len(true_df))

      end = time.time()

    eco2ai_tracker.stop()

    y_true = true_df['y'].values
    y_pred = forecast[model_name].values

    carbontracker_g = carbontracker.co2_g
    carbontracker_kWh = carbontracker.energy_kwh
    carbontracker_Wh = carbontracker_kWh * 1000 if carbontracker_kWh else None

    eco2ai_data = pd.read_csv("eco2ai_emissions_dl.csv").iloc[-1]
    eco2ai_kWh = eco2ai_data["power_consumption(kWh)"]
    eco2ai_Wh = eco2ai_kWh * 1000
    eco2ai_kg = eco2ai_data["CO2_emissions(kg)"]
    eco2ai_g = eco2ai_kg * 1000

    results.append({
      "Dataset": dataset_name,
      "Modelo": model_name,
      "Parâmetros": str(model),
      "SMAPE": smape(y_true, y_pred),
      "MAE": mean_absolute_error(y_true, y_pred),
      "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
      "CarbonTracker CO₂ (g)": carbontracker_g,
      "CarbonTracker Consumo (Wh)": carbontracker_Wh,
      "Eco2AI CO₂ (g)": eco2ai_g,
      "Eco2AI Consumo (Wh)": eco2ai_Wh,
      "Tempo (s)": end - start,
      "y_true": json.dumps(y_true.tolist()),
      "y_pred": json.dumps(y_pred.tolist())
    })

  return results

/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '620.2497460842133' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.002547232454038309' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0002880130263456576' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array

In [ ]:
data_path = "../datasets modificados"

In [ ]:
etth2 = load_series(f'{data_path}/wavelet_whiteNoise_ETTh2.csv', 'etth2')
electricity = load_series(f'{data_path}/wavelet_whiteNoise_electricity.csv', 'electricity')
traffic = load_series(f'{data_path}/magnitudeWarp_traffic.csv', 'traffic')
covid19 = load_series(f'{data_path}/shifted_Covid-19.csv', 'covid19')
retail = load_series(f'{data_path}/scaling_retail.csv', 'retail')
wike2000 = load_series(f'{data_path}/scaling_wike2000.csv', 'wike2000')
carbon = load_series(f'{data_path}/carbon.csv', 'carbon')

In [ ]:
etth2_train = etth2[(etth2['ds'] >= '2016-07-12 06:00:00') & (etth2['ds'] <= '2016-09-20 05:00:00')]
etth2_true = etth2[etth2['ds'] > '2016-09-20 05:00:00'].iloc[:24]

electricity_train = electricity[(electricity['ds'] >= '2013-06-28 07:00:01') & (electricity['ds'] <= '2013-09-06 06:00:01')]
electricity_true = electricity[electricity['ds'] > '2013-09-06 06:00:01'].iloc[:24]

traffic_train = traffic[(traffic['ds'] >= '2018-01-10 03:00:00') & (traffic['ds'] <= '2018-03-21 02:00:00')]
traffic_true = traffic[traffic['ds'] > '2018-03-21 02:00:00'].iloc[:24]

covid19_train = covid19[(covid19['ds'] >= '2021-03-12') & (covid19['ds'] <= '2022-03-10')]
covid19_true = covid19[covid19['ds'] > '2022-03-10'].iloc[:7]


retail_train = retail[(retail['ds'] >= '2017-01-01') & (retail['ds'] <= '2017-12-30')]
retail_true = retail[retail['ds'] > '2017-12-30'].iloc[:7]

wike2000_train = wike2000[(wike2000['ds'] >= '2012-07-08') & (wike2000['ds'] <= '2013-07-06')]
wike2000_true = wike2000[wike2000['ds'] > '2013-07-06'].iloc[:7]

carbon_train = carbon[(carbon['ds'] >= '2025-02-14') & (carbon['ds'] <= '2026-02-12')]
carbon_true = carbon[carbon['ds'] > '2026-02-12'].iloc[:7]

In [ ]:
etth2_train

                      ds          y unique_id
0    2016-07-12 06:00:00  37.224386     etth2
1    2016-07-12 07:00:00  36.876556     etth2
2    2016-07-12 08:00:00  37.694396     etth2
3    2016-07-12 09:00:00  39.848802     etth2
4    2016-07-12 10:00:00  41.690677     etth2
...                  ...        ...       ...
1675 2016-09-20 01:00:00  28.586860     etth2
1676 2016-09-20 02:00:00  28.018986     etth2
1677 2016-09-20 03:00:00  27.641455     etth2
1678 2016-09-20 04:00:00  26.437257     etth2
1679 2016-09-20 05:00:00  25.708770     etth2

[1680 rows x 3 columns]

/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '380.2461738586426' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0016307111833105895' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00018438288278574506' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '390.2597827911377' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0016670196816618876' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00018848824838582797' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '400.2507998943329' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0017030485126297004' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0001925619922745276' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '410.2418818473816' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0017412229526752993' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00019687833803604343' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '420.24276995658875' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.001777853319846816' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00020102009702175963' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '430.2592260837555' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0018264503911140887' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0002065149192728789' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '440.2598969936371' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.001862338246483117' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00021057272319159956' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '450.25699520111084' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0018990353321990043' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0002147220259764092' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '460.24292755126953' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0019369049437579374' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00021900390508576624' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '470.24609565734863' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0019731712113797636' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0002231044956994985' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '480.2601890563965' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array

In [ ]:
all_results = []

all_results += run_forecast(etth2_train, etth2_true, freq='h', season_length=24, dataset_name='ETTh2')
all_results += run_forecast(electricity_train, electricity_true, freq='h', season_length=24, dataset_name='Electricity')
all_results += run_forecast(traffic_train, traffic_true, freq='h', season_length=24, dataset_name='Traffic')
all_results += run_forecast(covid19_train, covid19_true, freq='d', season_length=7, dataset_name='Covid-19')
all_results += run_forecast(retail_train, retail_true, freq='d', season_length=7, dataset_name='Retail')
all_results += run_forecast(wike2000_train, wike2000_true, freq='d', season_length=7, dataset_name='Wike2000')
all_results += run_forecast(carbon_train, carbon_true, freq='d', season_length=7, dataset_name='Carbon')

Seed set to 1
Seed set to 1
Seed set to 1

Rodando Modelo:  TCN pro Dataset:  ETTh2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name            | Type                       | Params | Mode  | FLOPs
-------------------------------------------------------------------------------
0 | loss            | MAE                        | 0      | train | 0
1 | padder_train    | ConstantPad1d              | 0      | train | 0
2 | scaler          | TemporalNorm               | 0      | train | 0
3 | hist_encoder    | TemporalConvolutionEncoder | 131 K  | train | 0
4 | context_adapter | Linear                     | 40.3 K | train | 0
5 | mlp_decoder     | MLP                        | 16.6 K | train | 0
-------------------------------------------------------------------------------
188 K     Trainable params
0         Non-trainable params
188 K     Total params
0.756     Total estimated model params size (MB)
37        Modules in train mode
0         Modules in eval mode
0         Total Flops
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '20.225003004074097' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0030090306564914465' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00034022808729883134' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '30.230062007904053' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.003238528243000924' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00036617714990787146' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '40.235758781433105' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0034698116050486246' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00039232812837124295' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '50.241191148757935' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.003702786170880627' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0004186703295553016' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '60.25072169303894' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.003927873853623254' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0004441207687553277' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '70.23087406158447' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.004159784332839161' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00047034265472979117' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '80.22502112388611' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.004381042624493051' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0004953601085088048' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '90.23046779632568' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.004614017259710094' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0005217023175381607' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '100.23897218704224' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.004847662331823539' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0005481203321969557' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '110.23355531692505' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.005207336256894584' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0005887883032308136' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.

Rodando Modelo:  NBEATS pro Dataset:  ETTh2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name         | Type          | Params | Mode  | FLOPs
---------------------------------------------------------------
0 | loss         | MAE           | 0      | train | 0
1 | padder_train | ConstantPad1d | 0      | train | 0
2 | scaler       | TemporalNorm  | 0      | train | 0
3 | blocks       | ModuleList    | 6.0 M  | train | 0
---------------------------------------------------------------
5.9 M     Trainable params
83.4 K    Non-trainable params
6.0 M     Total params
23.807    Total estimated model params size (MB)
31        Modules in train mode
0         Modules in eval mode
0         Total Flops
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:02:58 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:03:08 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:03:18 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:03:28 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:03:38 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:03:48 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:03:58 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:04:08 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
`Trainer.fit` stopped: `max_steps=700` reached.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '88.93330025672913' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.001560820424379178' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.00017648040456412929' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array
/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/eco2ai/emission_track.py:515: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  attributes_dataframe.loc[row_index] = attributes_array

Rodando Modelo:  AUTOFORMER pro Dataset:  ETTh2

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type          | Params | Mode  | FLOPs
----------------------------------------------------------------
0 | loss          | MAE           | 0      | train | 0
1 | padder_train  | ConstantPad1d | 0      | train | 0
2 | scaler        | TemporalNorm  | 0      | train | 0
3 | decomp        | SeriesDecomp  | 0      | train | 0
4 | enc_embedding | DataEmbedding | 384    | train | 0
5 | dec_embedding | DataEmbedding | 384    | train | 0
6 | encoder       | Encoder       | 148 K  | train | 0
7 | decoder       | Decoder       | 141 K  | train | 0
----------------------------------------------------------------
290 K     Trainable params
0         Non-trainable params
290 K     Total params
1.162     Total estimated model params size (MB)
85        Modules in train mode
0         Modules in eval mode
0         Total Flops

OutOfMemoryError: CUDA out of memory. Tried to allocate 840.00 MiB. GPU 0 has a total capacity of 19.58 GiB of which 416.19 MiB is free. Process 928019 has 1.41 GiB memory in use. Including non-PyTorch memory, this process has 17.73 GiB memory in use. Of the allocated memory 17.48 GiB is allocated by PyTorch, and 8.87 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:04:28 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:04:38 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:04:48 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:04:58 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:05:08 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:05:18 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:05:28 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:05:38 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:05:48 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:05:58 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:06:08 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:06:18 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:06:28 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:06:38 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:06:48 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:06:58 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:07:08 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:07:18 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:07:28 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:07:38 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:07:48 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:07:58 -03)" to executor "default"
Traceback (most recent call last):
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 1195, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/base.py", line 74, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/enginelab/Neurips 2026/.venv/lib/python3.12/site-packages/apscheduler/executors/pool.py", line 27, in _do_submit_job
    f = self._pool.submit(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Error submitting job "Tracker._func_for_sched (trigger: interval[0:00:10], next run at: 2026-05-04 07:08:08 -03)" to executor "default"
Traceback (most recent call last):

In [ ]:
results_df = pd.DataFrame(all_results)
results_df.to_csv("../experiments/deep learning/experimentos_dl.csv", index=False)
results_df

,Dataset,Modelo,Parâmetros,SMAPE,MAE,RMSE,CarbonTracker CO₂ (g),CarbonTracker Consumo (Wh),Eco2AI CO₂ (g),Eco2AI Consumo (Wh),Tempo (s),y_true,y_pred
0,ETTh2,RandomForest,RandomForestRegressor(),20.96,6.771467,8.500905,0.001633,0.015823,0.002674,0.023653,0.448601,"[25.35650062561035, 25.136999130249023, 27.333...","[25.732299938201905, 25.72571994781494, 25.732..."
1,ETTh2,XGBoost,"XGBRegressor(base_score=None, booster=None, ca...",19.36,6.170565,8.037044,0.001573,0.015238,0.002532,0.022393,0.376004,"[25.35650062561035, 25.136999130249023, 27.333...","[25.038986206054688, 24.706754684448242, 24.89..."
2,ETTh2,CatBoost,"CatBoostRegressor(loss_function='RMSE', verbos...",15.96,5.232525,7.354678,0.002598,0.025170,0.003299,0.029180,0.584575,"[25.35650062561035, 25.136999130249023, 27.333...","[26.690334400514736, 27.273893988399145, 27.71..."
3,Electricity,RandomForest,RandomForestRegressor(),9.93,0.073954,0.149355,0.002471,0.023938,0.003204,0.028337,0.547240,"[-1.376244106473734, -1.2267854542201622, -0.8...","[-1.403984393904747, -1.209235962154592, -0.18..."
4,Electricity,XGBoost,"XGBRegressor(base_score=None, booster=None, ca...",21.05,0.180516,0.269628,0.000668,0.006472,0.001998,0.017670,0.152892,"[-1.376244106473734, -1.2267854542201622, -0.8...","[-1.401699185371399, -1.2174557447433472, 0.07..."
5,Electricity,CatBoost,"CatBoostRegressor(loss_function='RMSE', verbos...",10.35,0.105156,0.131261,0.002230,0.021602,0.003017,0.026684,0.496268,"[-1.376244106473734, -1.2267854542201622, -0.8...","[-1.3526986956722638, -1.188026044321824, -0.5..."
6,Transporte,RandomForest,RandomForestRegressor(),13.27,76.507500,132.846114,0.002079,0.020139,0.002930,0.025909,0.472237,"[680.0, 810.0, 1131.0, 1346.0, 1194.0, 792.0, ...","[693.35, 733.62, 1016.1, 1374.54, 1131.99, 831..."
7,Transporte,XGBoost,"XGBRegressor(base_score=None, booster=None, ca...",38.54,76.619410,138.746706,0.000504,0.004881,0.001818,0.016080,0.112118,"[680.0, 810.0, 1131.0, 1346.0, 1194.0, 792.0, ...","[642.0361938476562, 725.8562622070312, 1014.60..."
8,Transporte,CatBoost,"CatBoostRegressor(loss_function='RMSE', verbos...",38.45,79.228495,137.304024,0.002253,0.021826,0.003056,0.027024,0.521380,"[680.0, 810.0, 1131.0, 1346.0, 1194.0, 792.0, ...","[658.7804124714141, 731.8366368922091, 1031.42..."
9,Covid-19,RandomForest,RandomForestRegressor(),48.80,2176.412857,2662.503682,0.000515,0.004988,0.001791,0.015843,0.114476,"[4184, 4194, 3614, 3116, 2503, 2568, 2876]","[4338.7, 4479.43, 4883.33, 5458.16, 5674.89, 6..."
10,Covid-19,XGBoost,"XGBRegressor(base_score=None, booster=None, ca...",48.08,2177.616455,2761.375020,0.000286,0.002769,0.001563,0.013825,0.068658,"[4184, 4194, 3614, 3116, 2503, 2568, 2876]","[4292.8359375, 4224.84326171875, 4749.84130859..."
11,Covid-19,CatBoost,"CatBoostRegressor(loss_function='RMSE', verbos...",67.92,3380.274403,3613.701309,0.001520,0.014723,0.002437,0.021549,0.354751,"[4184, 4194, 3614, 3116, 2503, 2568, 2876]","[5528.144720466691, 5998.589545869123, 6689.33..."
12,Varejo,RandomForest,RandomForestRegressor(),47.91,28.290889,46.002408,0.000502,0.004862,0.001620,0.014328,0.121766,"[78.43500000000004, 0.0, 125.11999999999998, 4...","[57.78402999999997, 115.90945000000004, 146.98..."
13,Varejo,XGBoost,"XGBRegressor(base_score=None, booster=None, ca...",59.30,41.370386,69.345252,0.000251,0.002434,0.001490,0.013178,0.062680,"[78.43500000000004, 0.0, 125.11999999999998, 4...","[37.999759674072266, 175.4629669189453, 135.06..."
14,Varejo,CatBoost,"CatBoostRegressor(loss_function='RMSE', verbos...",51.25,32.857557,53.611573,0.001360,0.013178,0.002336,0.020660,0.348487,"[78.43500000000004, 0.0, 125.11999999999998, 4...","[46.988391070055954, 134.28975858124073, 142.9..."
15,Wike2000,RandomForest,RandomForestRegressor(),13.07,433.461429,464.597665,0.000462,0.004479,0.001632,0.014432,0.120151,"[1567.0, 4609.0, 4766.0, 4830.0, 4623.0, 3902....","[1292.58, 4027.63, 4119.78, 4244.18, 4162.27, ..."
16,Wike2000,XGBoost,"XGBRegressor(base_score=None, booster=None, ca...",20.20,701.702619,814.112883,0.000521,0.005045,0.001750,0.015478,0.122258,"[1567.0, 4609.0, 4766.0, 4830.0, 4623.0, 3902....","[1255.81884765625, 3862.807861328125, 3860.685..."
17,Wike2000,CatBoost,"CatBoostRegressor(loss_function='RMSE', verbos...",12.12,439.957101,493.260767,0.001491,0.014447,0.002281,0.020176,0.387429,"[1567.0, 4609.0, 4766.0, 4830.0, 4623.0, 3902....","[1411.0140525425754, 4186.297510442272, 4353.1..."
18,Carbon,RandomForest,RandomForestRegressor(),7.79,8.394421,8.885057,0.000472,0.004574,0.001700,0.015034,0.113010,"[108.384965034, 104.169610454, 101.285553346, ...","[110.31028700722857, 111.95101489995312, 112.6..."
19,Carbon,XGBoost,"XGBRegressor(base_score=None, booster=None, ca...",8.15,8.801020,9.213548,0.000310,0.003002,0.001622,0.014348,0.073710,"[108.384965034, 104.169610454, 101.285553346, ...","[111.94823455810547, 112.05225372314453, 113.8..."
20,Carbon,CatBoost,"CatBoostRegressor(loss_function='RMSE', verbos...",7.98,8.606020,9.042893,0.001322,0.012813,0.002226,0.019690,0.345690,"[108.384965034, 104.169610454, 101.285553346, ...","[110.63148545219954, 112.45002868851792, 112.4..."